### PR TITLE
Enable PostSRSd to avoid being marked as spam by failed SPF checks.

### PR DESCRIPTION
**Pull request by budoteam**
Forwarding to a gmail account never worked for me.  The problem was that the SPF check always failed. However, the problem was not my SPF entry, but that of the sender.
After some research I found the solution: SRS (Sender Rewriting Scheme). The sender is replaced by a temporary sender from my domain and the SPF check passes.
The required daemon was already installed in the container, but unfortunately not activated. With a few lines of code the daemon can be activated, a security key generated and Postfix configured so that now everything works.
My mails now no longer end up as spam \o/.

I ask you to consider the changes and optionally enable SRS in the original branch.
Thank you for your time

[SRS](https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme)

### CODE REVIEW

**Comment by tamaro-skaljic** [comment]
@huan

**Review by huan — APPROVED** [review]
Thank you very much for your contribution!

It seems that this PR is good to me, however, could you please try to invite more contributors to approve this PR so that we can merge it with enough confidence?

**Review by dimitrovs — APPROVED** [review]

**Comment by huan** [comment]
@dimitrovs Thank you very much for the approval!

**Comment by goodprogrammist** [comment]
Hi! 

Can you help me with SRS?

With SRS active i get "NOQUEUE: reject: RCPT from Temporary lookup failure"
Tried sending to myself from google, sendinblue, protonmail - all of them failed with this error

Postfix log (part with protonmail):

Sep 22 09:05:36 mx8 postfix/smtpd[1980]: warning: unknown[31.130.184.93]: SASL LOGIN authentication failed: authentication failure
Sep 22 09:05:37 mx8 postfix/smtpd[2233]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
Sep 22 09:05:38 mx8 postfix/smtpd[1980]: disconnect from unknown[31.130.184.93] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Sep 22 09:05:38 mx8 postfix/smtpd[2233]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
Sep 22 09:05:39 mx8 postfix/smtpd[2233]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
Sep 22 09:05:40 mx8 postfix/smtpd[2233]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
Sep 22 09:05:41 mx8 postfix/smtpd[1980]: connect from unknown[31.130.184.93]
Sep 22 09:05:41 mx8 postfix/smtpd[2233]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
Sep 22 09:05:41 mx8 postfix/smtpd[2051]: warning: unknown[31.130.184.93]: SASL LOGIN authentication failed: authentication failure
Sep 22 09:05:42 mx8 postfix/smtpd[2233]: warning: connect to TCP map 127.0.0.1:10002: Connection refused
Sep 22 09:05:42 mx8 postfix/smtpd[2233]: warning: tcp:127.0.0.1:10002 lookup error for "hp@mx8.omexo.ru"
Sep 22 09:05:42 mx8 postfix/smtpd[2233]: NOQUEUE: reject: RCPT from mail-0201.mail-europe.com[51.77.79.158]: 451 4.3.0 <hp@mx8.omexo.ru>: Temporary lookup failure; from=<dev8ops@protonmail.com> to=<hp@mx8.omexo.ru> proto=ESMTP helo=<mail-0201.mail-europe.com>
Sep 22 09:05:42 mx8 postfix/smtpd[2233]: disconnect from mail-0201.mail-europe.com[51.77.79.158] ehlo=2 starttls=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=6/8
Sep 22 09:05:42 mx8 postfix/smtpd[2051]: disconnect from unknown[31.130.184.93] ehlo=1 auth=0/1 rset=1 quit=1 commands=3/4
Sep 22 09:05:45 mx8 postfix/smtpd[1980]: warning: unknown[31.130.184.93]: SASL LOGIN authentication failed: authentication failure

**Pull request merged**
