### PR TITLE
Allow for setting any Postfix variables in the config file (both main.cf and master.cf)

### PR DESCRIPTION
**Pull request by dgraziotin**
As presented in #92, this PR enables SMF to recognize environment variables that start with SMF_POSTFIXMAIN_ and SMF_POSTFIXMASTER_ to set option entries for postfix main.cf and master.cf, respectfully.

Provided in this PR:

- Functionality
- Tests
- Updated README.md

### CODE REVIEW

**Comment by dgraziotin** [comment]
@huan I know the drill, but I do not know who to call to review this one :-) care to name a good reviewer? Thanks!

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
@dgraziotin Thank you very much for taking this new feature and create this great PR with docs & unit tests!

I feel it's good, please try to get at least one more approval from any SMF users then I'll be very confident to merge this PR!

**Comment by dgraziotin** [comment]
@huan thanks! Unfortunately, I am not familiar with SMF users and would like to avoid asking again to the same one (not even tagging them here 😄). Would you have any suggestions?

**Comment by huan** [comment]
Ok, let's merge this PR for now, and please test it and make sure the published image works as expected.

Thanks for the contribution, appreciate it!

**Comment by dgraziotin** [comment]
Thanks @huan! I have SMF in production on 3 servers and make use of this feature. I will certainly test it over time and come back here with bug fixes, in case!

**Pull request merged**
