### PR TITLE
EC key support

### PR DESCRIPTION
**Pull request by Czocher**
This change add EC key support for simple-mail-forwarder.
Also fixes a little typo.
Solves #50

### CODE REVIEW

**Comment by huan** [comment]
It looks good to me, I'll merge it first.

However, please test it after the new docker image had been published and make sure it works as you expected.

Thank you very much for bring this new feature to the SMF!

**Comment by huan** [comment]
@Czocher I had just fixed a bug introduced from this PR that broke the unit testing.

**Comment by Czocher** [comment]
@huan I'm extremely sorry, haven't realized there were unit tests in this project!

**Comment by huan** [comment]
Of course we have! ;-)

**Comment by petslane** [comment]
I think this PR has some problems...

I used `letsencrypt` to generate `fullchain.pem` and `privkey.pem` and used them as `smtp.cert` and `smtp.key` in folder that is mouted as `/etc/postfix/cert/` in container.

When starting `latest`/`1.1` image, then server starts correctly, no errors in logs, but when configuring smtp server in gmail, then I get error:
> Authentication failed. Please check your username/password.
Server returned error: "TLS Negotiation failed, the certificate doesn't match the host., code: 0"

Tested certs with https://www.checktls.com/TestReceiver and cert test fails:
image

Details about cert fail:

> ```
> 	Cert VALIDATION ERROR(S): self signed certificate
> So email is encrypted but the recipient domain is not verified
> Cert Hostname DOES NOT VERIFY (mail.example.com != simple-mail-forwarder.com)
> So email is encrypted but the host is not verified
> cert not revoked by OCSP
> Data:
>   Version: n/a
>   Serial Number: 99:7b:00:b0:9a:d6:ff:88
>   Validity:
>     Not Before: Sep  7 15:05:26 2020 GMT
>     Not After: Sep  5 15:05:26 2030 GMT
>   Issuer:
>     commonName =	simple-mail-forwarder.com
>     countryName =	US
>     localityName =	L
>     organizationName =	O
>     stateOrProvinceName =	Matrix
>   Subject:
>     commonName =	simple-mail-forwarder.com
>     countryName =	US
>     localityName =	L
>     organizationName =	O
>     stateOrProvinceName =	Matrix
>   Subject Public Key Info:
>     Public Key Algorithm: id-ecPublicKey
>     Public Key Bits: (384 bit)
>     Modulus:
>       49:F6:54:70:FF:D0:4F:75:A9:A3:53:BE:E5:FB:74:44
> [...]
>       B
>     Exponent: n/a
>     Key:
>       -----BEGIN PUBLIC KEY-----
>       MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEn2VHD/0E91qaNTvuX7dET+ZcuzKLg3ZV
> [...]
>       -----END PUBLIC KEY-----
>   X509v3 Extensions:
> Digest: 8aa3ee4ff9e1a701ee47b0c17a291228b03341e5ef7076f01ebfcad1aea369a2
> Signature: ecdsa-with-SHA256
>   6d:61:69:6c:2d:66:6f:72:77:61:72:64:65:72:2e:63
> [...]
> Fingerprints:
>   sha256$8aa3ee4ff9e1a701ee47b0c17a291228b03341e5ef7076f01ebfcad1aea369a2
> [...]
>   sha512$pub$163ac8d3d075fe6a910e956a58bbe122fc06f21d662b14ec39bacfcad18c97f370415df2fc14ef6732c2c383f439d9b4a5a7437a4280f1d7f2bbb4bc4c9ea359
> Certificate:
>   -----BEGIN CERTIFICATE-----
>   MIIB4TCCAWcCCQCZewCwmtb/iDAKBggqhkjOPQQDAjBaMQswCQYDVQQGEwJVUzEP
> [...]
>   E13NIJM=
>   -----END CERTIFICATE-----
> ```

After starting container, I noticed that `smtp.ec.cert` and `smtp.ec.key` files were also generated. I do not know what exactly are they, but I think these are not needed.

Stopped container, deleted `smtp.ec.cert` and `smtp.ec.key` files, changed image to `1.0.0` and started container. Now `smtp.ec.cert` and `smtp.ec.key` files were not created and all tests pass on https://www.checktls.com/TestReceiver. Also, now gmail allows it to use as SMTP.

**Comment by ggilestro** [comment]
The following works for me:

```
cp ../../archive/mydomain/fullchain2.pem smtp.cert
cp ../../archive/mydomain/fullchain2.pem smtp.ec.cert
cp ../../archive/mydomain/privkey2.pem smtp.ec.key
cp ../../archive/mydomain/privkey2.pem smtp.key
```
Basically, the ec files are just a copy of the non-ec files.

**Comment by petslane** [comment]
I can confirm that `cp smtp.cert smtp.ec.cert && cp smtp.key smtp.ec.key` fixes latest image.

If these "ec" cert/key are required when using letsencrypt (or any other certs?), then I think README should explicitly mention that these files must be copied there.

**Pull request merged**
