### PR TITLE
add auth for relayhost

### PR DESCRIPTION
**Pull request by Jeffrey04**
After a couple of searches I found a way to send mail through `SMF_RELAYHOST` that require login, and got it working.

### CODE REVIEW

**Comment by huan** [comment]
Thank you very much for your contribution!

Cloud you please:

1. document your new feature in README, so that the users could be able to learn how to use it?
1. indent your shell code correctly with the original code.

**Comment by Jeffrey04** [comment]
done

**Comment by Jeffrey04** [comment]
also accidentally found a fix for mail log not displaying, so attaching it here

**Comment by huan** [comment]
Great work!

Appreciate for the fix & improvement.

**Comment by Jeffrey04** [comment]
no worries, just needed to get this work so i can cancel my mailgun subscription heh (:

**Pull request merged**
