### PR TITLE
Strips sender details (IP, client, user agent) when sending

### PR DESCRIPTION
**Pull request by dgraziotin**
This PR enables, when the env variable `SMF_SENDERPRIVACY` is defined, stripping of headers related to the sender, when SMF is used to send e-mails (outgoing e-mail).

In particular, IP, client, and user agent will be removed, but only from the first `Received` instance, for sending. 

The first `Received:` header (the one below) will be rewritten as so:

```
Received: from smfdomain.com ( smfdomain.com [123.123.123.123])
	(using TLSv1.2 with cipher ADH-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail-tester.com (Postfix) with ESMTPS id XXX
Received: from 127.0.0.1 (localhost [127.0.0.1])
	by smfdomain.com (Postfix) with ESMTPSA id XXX
```

where `smfdomain.com` is SMF rDNS entry. In other words, only SMF IP address will be visible to the receiver but not the client (home) IP address.

### CODE REVIEW

**Comment by dgraziotin** [comment]
@huan sorry for not telling in advance. I needed this feature so I simply went and implemented it. What do you think?

**Comment by huan** [comment]
I think this feature is useful in some scenarios, thanks for adding it!

Could you please invite someone to review your code and approve it for us?

It will be enough confidence for me after at least one approvement and I'll be very happy to merge it then!

**Comment by dgraziotin** [comment]
Well, I know that @petslane likely uses SMF for sending. Otherwise I do not know the community here, sorry!

**Comment by petslane** [comment]
LGTM

**Comment by huan** [comment]
@dgraziotin Thank you very much for add this new feature to SMF!
@petslane Thank you very much for review the PR and approve it!

SMF growth in recent years based on pure community efforts, without helps from the community the SMF can not move forward like this. appreciate!

**Comment by dgraziotin** [comment]
@huan thank YOU for this awesome image.

**Pull request merged**
